# Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# Answer:  4613732


# Execution time: ~0.00700 ms
# collect Fibonacci sequence and even Fibonacci nums as lists
# test evenness with modulo
# return sum of even num list
def fib_even_sum_brute(ceiling:int) -> int:
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    fibs = [1,2]
    efibs = [2]
    while fibs[-1] <= ceiling:
        fibs.append(fibs[-1] + fibs[-2])
        if (fibs[-1] % 2 == 0):
            efibs.append(fibs[-1])
    return sum(efibs)


# collect last two Fibonacci nums as ints, even Fibonacci nums as list
# test evenness with modulo
# return sum of even num list
def fib_even_sum_prev_next(ceiling:int) -> int: # ~2/3 the time of brute version
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    [prev, curr] = [1, 2]
    efibs = [2]
    while curr <= ceiling:
        nxt = prev + curr
        if (nxt % 2 == 0):
            efibs.append(nxt)
        prev = curr
        curr = nxt
    return sum(efibs)


#WINNER WINNER CHICKEN DINNER!!
# Execution time: 0.00487 ms
# collect last two Fibonacci nums as ints
# keep a running total of even Fibonacci numbers
# test evenness with modulo
# return final total
def fib_even_sum_prev_next_totaling(ceiling:int) -> int: # ~1/2 the time of brute version
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    [prev, curr] = [1, 2]
    efib_total = 2
    while curr <= ceiling:
        nxt = prev + curr
        if (nxt % 2 == 0): efib_total += nxt
        prev = curr
        curr = nxt
    return efib_total


# what if I used lambda instead of:  if (nxt % 2 == 0): efib_total += nxt
def fib_even_sum_lambda(ceiling: int) -> int: # nope, ~= brute approach
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    [prev, curr] = [1, 2]
    efib_total = 2
    while curr <= ceiling:
        nxt = prev + curr
        efib_total += (lambda x : x if x % 2 == 0 else 0)(nxt)
        prev = curr
        curr = nxt
    return efib_total


### -------------- REGEX EXPERIMENTS -------------- ###

# CONCLUSION:  PURE MATCH is always BETTER!!!

# The next trials are all using REGEX for num to string matching of last digit for evenness
import re # for next versions...

# test evenness with regex and stringed next value
def fib_even_sum_regex_test(ceiling:int) -> int: # a little worse than brute solution
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    even_test = r".*[02468]$" # test last digit for evenness
    [prev, curr] = [1, 2]
    efib_total = 2
    while curr <= ceiling:
        nxt = prev + curr
        if re.fullmatch(even_test, str(nxt)):
            efib_total += nxt
        prev = curr
        curr = nxt
    return efib_total


# compile the regular expression to test last digit of next Fibonacci value for evenness
# test evenness with regex and stringed next value
def fib_even_sum_regex_test_compiled(ceiling:int) -> int: # a little better than brute solution
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    even_test = re.compile(r".*[02468]$") # test last digit for evenness
    [prev, curr] = [1, 2]
    efib_total = 2
    while curr <= ceiling:
        nxt = prev + curr
        if even_test.fullmatch(str(nxt)):
            efib_total += nxt
        prev = curr
        curr = nxt
    return efib_total

# test evenness with regex match and last indexed digit of stringed next value
def fib_even_sum_regex_test_last_digit(ceiling:int) -> int: # 5X WORSE than brute solution -- absolutely worst!!
    # edge case: ceiling less than 2
    if ceiling < 2:
        return 0
    even_test = re.compile(r"[02468]") # test last digit for evenness
    [prev, curr] = [1, 2]
    efib_total = 2
    while curr <= ceiling:
        nxt = prev + curr
        if even_test.match(str(nxt)[-1]):
            efib_total += nxt
        prev = curr
        curr = nxt
    return efib_total






### ----------------- TIME THE EXECUTION ----------------- ###
def test():
    return 'Hey Joe, whadya know?'

import time

# PRETRIAL -- don't know why I need to run the same first function 2ce, but if I don't this function gives higher ms
start_time = time.perf_counter_ns()
fib_even_sum_brute(4000000) # 4613732
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for PRETRIAL: {elapsed_ms:.5f} ms")


# TRIAL 1
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_brute(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 1: {elapsed_ms:.5f} ms")


# TRIAL 2
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_prev_next(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 2: {elapsed_ms:.5f} ms")


# TRIAL 3
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_prev_next_totaling(4000000)) # 4613732
# print(fib_even_sum_prev_next_totaling(-1)) # 0
# print(fib_even_sum_prev_next_totaling(1)) # 0
# print(fib_even_sum_prev_next_totaling(2)) # 2
# print(fib_even_sum_prev_next_totaling(3)) # 2

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 3: {elapsed_ms:.5f} ms")


# TRIAL 4
start_time = time.perf_counter_ns()

print(fib_even_sum_lambda(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 4: {elapsed_ms:.5f} ms")


### REGEX TESTS ###
print('/n*******regex versions*******/n')
import re

# PRETRIAL 2
# run one of these the first time because it runs way longer.  Then running again is much shorter.
start_time = time.perf_counter_ns()
fib_even_sum_regex_test(4000000)
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6

# TRIAL 5
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_regex_test(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 5: {elapsed_ms:.5f} ms")


# TRIAL 6
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_regex_test_compiled(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 6: {elapsed_ms:.5f} ms")


# TRIAL 7
start_time = time.perf_counter_ns()

# run the function
print(fib_even_sum_regex_test_last_digit(4000000)) # 4613732

# print time elapsed
elapsed_ms = (time.perf_counter_ns() - start_time) / 1e6
print(f"Execution time for TRIAL 7: {elapsed_ms:.5f} ms")